### PR TITLE
Add Binder support 

### PR DESCRIPTION
**Pull request by matthewfeickert**
Add a Binder badge to the `README` that launches directly into the [PlotContour notebook](https://github.com/lukasheinrich/lhoodbinder2/blob/master/PlotContour.ipynb) in a ~~Jupyter lab~~ Jupyter server environment.

[Binder](https://mybinder.org/v2/gh/lukasheinrich/lhoodbinder2/master?filepath=PlotContour.ipynb)

### CODE REVIEW

**Comment by lukasheinrich** [comment]
udeally this would launch in jupyter notebook rather than jupyer lab.. the %matplotlib notebook magic doesn't work in lab

**Comment by matthewfeickert** [comment]
> udeally this would launch in jupyter notebook rather than jupyer lab.. the %matplotlib notebook magic doesn't work in lab

Gotcha. Will change now.

**Comment by matthewfeickert** [comment]
@lukasheinrich Fixed.

**Comment by lukasheinrich** [comment]
thanks @matthewfeickert

**Pull request merged**
